
version: '3'

services:
  hello:
    build: .
    ports:
    - "8000:8000"
    command: ["node","app.js"]
  selenium-hub:
        image: selenium/hub:3.11.0-dysprosium
        container_name: selenium-hub
        ports:
          - "4444:4444"
  chrome:
        image: selenium/node-chrome-debug:3.11.0-dysprosium
        volumes:
           - /dev/shm:/dev/shm
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444
        ports:
            - 5900
  firefox:
        image: selenium/node-firefox-debug:3.11.0-dysprosium
        volumes:
         - /dev/shm:/dev/shm
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444
        ports:
            - 5900